/**
 * Client-side export — zero dependencies. Builds a CSV of the user's local
 * records (wins, journey progress, recovery profile summary) and a printable
 * HTML summary (browser "Save as PDF"). Nothing leaves the device unless the
 * user saves/prints it themselves.
 */
import { loadWins } from "./wins";
import { loadProfile, deriveRecovery } from "./recoveryProfile";

function download(filename: string, content: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function csvEscape(v: string): string {
  if (/[",\n]/.test(v)) return `"${v.replace(/"/g, '""')}"`;
  return v;
}

export function exportCSV(): void {
  const wins = loadWins();
  const rows: string[][] = [["type", "date", "detail"]];
  wins.forEach((w) => rows.push(["win", w.date, w.text]));

  const profile = loadProfile();
  if (profile.onboardingCompleted) {
    const d = deriveRecovery(profile);
    rows.push(["profile", new Date().toISOString().split("T")[0], `Goal: ${d.primaryGoal}; Trigger: ${d.topTrigger}; Risk time: ${d.highRiskTime}`]);
  }

  const csv = rows.map((r) => r.map(csvEscape).join(",")).join("\n");
  download(`reset-export-${new Date().toISOString().split("T")[0]}.csv`, csv, "text/csv;charset=utf-8");
}

export function exportSummary(): void {
  const wins = loadWins();
  const profile = loadProfile();
  const d = profile.onboardingCompleted ? deriveRecovery(profile) : null;
  const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  const winItems = wins.length
    ? wins.slice(0, 40).map((w) => `<li><span class="d">${new Date(w.date).toLocaleDateString()}</span> ${escapeHtml(w.text)}</li>`).join("")
    : "<li>No victories recorded yet.</li>";

  const html = `<!doctype html><html><head><meta charset="utf-8"><title>RESET summary</title>
  <style>
    body{font-family:-apple-system,'Segoe UI',sans-serif;max-width:640px;margin:40px auto;padding:0 24px;color:#1C2333;line-height:1.6}
    h1{font-size:26px;margin:0 0 4px} .sub{color:#5A6478;margin:0 0 28px}
    h2{font-size:14px;text-transform:uppercase;letter-spacing:.08em;color:#646E80;margin:28px 0 10px}
    ul{padding-left:18px;margin:0} li{margin:4px 0} .d{color:#8A93A6;font-size:12px;margin-right:6px}
    .row{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid #E6EAF2}
    .foot{margin-top:36px;font-size:12px;color:#8A93A6}
  </style></head><body>
  <h1>Your RESET summary</h1>
  <p class="sub">${today} — private to you</p>
  ${d ? `<h2>Recovery profile</h2>
  <div class="row"><span>Primary goal</span><strong>${escapeHtml(d.primaryGoal)}</strong></div>
  <div class="row"><span>Most common trigger</span><strong>${escapeHtml(d.topTrigger)}</strong></div>
  <div class="row"><span>Highest-risk time</span><strong>${escapeHtml(d.highRiskTime)}</strong></div>
  <div class="row"><span>Focus</span><strong>${escapeHtml(d.weeklyFocus)}</strong></div>` : ""}
  <h2>Victories (${wins.length})</h2>
  <ul>${winItems}</ul>
  <p class="foot">Generated by RESET. This is your own record — RESET supports recovery but is not a replacement for professional care.</p>
  </body></html>`;

  const w = window.open("", "_blank");
  if (w) {
    w.document.write(html);
    w.document.close();
    // Give the browser a tick to render before opening the print/Save-as-PDF dialog.
    setTimeout(() => w.print(), 350);
  } else {
    // Popup blocked — fall back to a downloaded HTML file the user can open + print.
    download(`reset-summary-${new Date().toISOString().split("T")[0]}.html`, html, "text/html");
  }
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c] as string));
}
